site_name: TRA VFD API Documentation
site_url: https://tra-docs.netlify.app/
site_author: Alpha Olomi
site_description: >-
  TRA VFD API Documentation for Developers

# Repository
repo_name: alphaolomi/tra-docs
repo_url: https://github.com/alphaolomi/tra-docs
edit_uri: edit/main/docs/

# Copyright
# copyright: Copyright &copy; 2021 Alpha Olomi
copyright: Copyright &copy; 2021 Alpha Olomi

nav:
  - Home: index.md
  - Guide:
    - Introduction: guide/introduction.md
    - API: guide/api.md
  - Integrations:
    - Node.js: integrations/nodejs.md
  - About: about.md
plugins:
  - search
  - git-revision-date
  - git-revision-date-localized:
      fallback_to_build_date: true
      

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  analytics:
    provider: google
    property: G-7D7ZB0C1E5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alphaolomi

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
