site_name: TRA VFD API Documentation

nav:
  - Home: index.md

theme: 
  name: material  
  analytics:
    gtag: G-7D7ZB0C1E5
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s